language:
    - java

services:
    - mysql

jdk:
    - oraclejdk8
    - openjdk7

before_install:
    - mysql -u root -e "CREATE DATABASE 'Acme\-Pad\-Thai';"
    - mysql -u root -e "CREATE USER 'acme-manager'@'%' IDENTIFIED BY 'ACME-M@n@ger-6874';"
    - mysql -u root -e "GRANT SELECT, INSERT, UPDATE, DELETE, CREATE, DROP, REFERENCES, INDEX, ALTER, CREATE TEMPORARY TABLES, LOCK TABLES, EXECUTE, CREATE VIEW, SHOW VIEW, CREATE ROUTINE, ALTER ROUTINE, TRIGGER ON *.* TO 'del-manager'@'%' IDENTIFIED BY 'ACME-M@n@ger-6874' WITH GRANT OPTION;"
    - mysql -u root -e "CREATE USER 'acme-user'@'%' IDENTIFIED BY 'ACME-Us3r-P@ssw0rd';"
    - mysql -u root -e "GRANT SELECT, INSERT, UPDATE, DELETE ON *.* TO 'del-user'@'%' IDENTIFIED BY 'ACME-Us3r-P@ssw0rd' WITH GRANT OPTION;"

script:
    - cd Acme-Pad-Thai
    - mvn clean test
    - ls -lah

before_deploy:
    - mvn clean compile war:war
    - cp initialize.sql populate.sql
    - sed -i".bak" '/commit;/d' populate.sql
    - mysqldump -u root deliberations >> populate.sql
    - echo "commit;" >> populate.sql
    - ls -lah

cache:
    directories:
        - $HOME/.m2   # Cache para las dependencias de maven

dist:
    - trusty

sudo:
    - false

notifications:
    - email: false  # Desactivamos las notificaciones por email para evitar spam
